version: '3.7'
services:
  app:
    image: openjdk:11
    container_name: scio-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  memcached:
    container_name: memcached
    image: memcached:alpine
    ports:
      - 11211:11211